# Generated by Django 3.1.14 on 2022-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('is_bad_food', models.BooleanField(default=False)),
            ],
        ),
    ]
